[theme]
base = "light"
primaryColor = "#111827"
backgroundColor = "#F4F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
